name: 'Page Speed Insights'

description: 'consume the output of the previous action and create a new issue in the repository'

inputs:
  lh:
    description: 'Fail the build if the threshold is not met.'
    default: 90
  fcp:
    description: 'Fail the build if the threshold is not met.'
    default: 1.8
  lcp:
    description: 'Fail the build if the threshold is not met.'
    default: 2.5
  tbt:
    description: 'Fail the build if the threshold is not met.'
    default: 200
  cls:
    description: 'Fail the build if the threshold is not met.'
    default: 0.1
  repo-token:
    default: ${{ github.token }}
    description: 'Token with permissions to do repo things'
  psi-key:
    description: 'The Page Speed Insights key'
  relative-url:
    default: '/'

runs:
  using: 'docker'
  image: 'Dockerfile'